name: Quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Rerun periodically to pick up new advisories
  schedule:
    - cron: '0 0 * * *'
  # Run manually
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://Joshua-Griffith_fnf:${{ secrets.TEMP_GH_ALL_REPOS_RW }}@github.com/
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Install clippy-sarif from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: clippy-sarif
      - name: Install sarif-fmt from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: sarif-fmt
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run:
          cargo clippy --all-features -- -D warnings
#          cargo clippy --all-features --message-format=json -- -D warnings
#          | clippy-sarif
#          | tee results.sarif
#          | sarif-fmt
#        continue-on-error: true
#      - name: Upload analysis results to GitHub
#        uses: github/codeql-action/upload-sarif@v3
#        with:
#          sarif_file: results.sarif
#          wait-for-processing: true
