name: Build Gems
on:
  push:
#    branches:
#      - main
#      - "releases/*"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  build-platform-gems:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rubyPlatform:
          - aarch64-linux
          - aarch64-linux-musl
          - x86_64-linux
          - x86_64-linux-musl
          - arm-linux
          - arm64-darwin
          - x86_64-darwin
          - x64-mingw-ucrt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://Joshua-Griffith_fnf:${{ secrets.TEMP_GH_ALL_REPOS_RW }}@github.com/

      - name: Setup Ruby and Rust
        uses: cincpro/oxidize-rb-actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          cargo-vendor: true
          cache-version: v1-${{ matrix.rubyPlatform }}
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: 'true'

      - name: Cross compile gem
        uses: cincpro/oxidize-rb-actions/cross-gem@v1
        id: cross-gem
        with:
          platform: ${{ matrix.rubyPlatform }}
          ruby-versions: "3.2,3.3,3.4"

      - name: Upload gem
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rubyPlatform }}-gem
          path: ${{ steps.cross-gem.outputs.gem-path }}

  build-source-gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://Joshua-Griffith_fnf:${{ secrets.TEMP_GH_ALL_REPOS_RW }}@github.com/

      - name: Setup Ruby and Rust
        uses: cincpro/oxidize-rb-actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          cache-version: v1-source
          token: ${{ secrets.GH_ALL_REPOS_RO }}
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: 'true'

      - name: Install bundle
        run: bundle install

      - name: Build
        run: bundle exec rake build

      - name: Upload gem
        uses: actions/upload-artifact@v4
        with:
          name: source-gem
          path: pkg/*.gem
